# Generated by Django 3.2.6 on 2021-08-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_agencyprofile_recruiterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='allowed_viwers',
            field=models.JSONField(default={}),
        ),
    ]
