# Generated by Django 3.2.6 on 2021-08-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profilemodel_allowed_viwers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='allowed_viwers',
            field=models.JSONField(default={'id': '[]'}),
        ),
    ]
