# Generated by Django 3.2.6 on 2021-08-28 08:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profilemodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='full_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=150), default=[], size=None),
        ),
    ]
