# Generated by Django 3.2.6 on 2021-08-28 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0012_auto_20210828_1414'),
        ('profiles', '0007_auto_20210828_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=250)),
                ('job_title', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('is_present', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='allowed_viwers',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='skills',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='userSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.skills', to_field='skill')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(default='', max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.degrees', to_field='degree')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
