# Generated by Django 3.2.6 on 2021-08-28 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0008_auto_20210828_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='authorizedViewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
                ('viewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
