# Generated by Django 3.2.6 on 2021-08-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_authorizedviewers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterprofile',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='last_name',
        ),
    ]
