# Generated by Django 3.2.6 on 2021-08-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210828_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='companyLogo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
