# Generated by Django 3.2.6 on 2021-08-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210828_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='bithdate',
            new_name='birthdate',
        ),
    ]
