# Generated by Django 3.2.6 on 2021-08-31 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_rename_bithdate_profilemodel_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_type',
            field=models.ForeignKey(default='Start-up', on_delete=django.db.models.deletion.CASCADE, to='profiles.companytypes', to_field='_type'),
        ),
    ]
