# Generated by Django 3.2.6 on 2021-08-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20210831_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterprofile',
            old_name='bithdate',
            new_name='birthdate',
        ),
    ]
