# Generated by Django 3.2.6 on 2021-09-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_rename_bithdate_recruiterprofile_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='salary',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.positions', to_field='position'),
        ),
    ]
