# Generated by Django 3.2.6 on 2021-09-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20210902_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='postion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.positions', to_field='position'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
