# Generated by Django 3.2.6 on 2021-09-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20210902_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='postion',
            new_name='position_id',
        ),
    ]
