# Generated by Django 3.2.6 on 2021-09-04 10:24

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20210902_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=profiles.models.uploadProfilePic),
        ),
    ]
