# Generated by Django 3.2.6 on 2021-10-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_profilemodel_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_description',
            field=models.TextField(default=''),
        ),
    ]
