# Generated by Django 3.2.6 on 2021-11-29 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_alter_experience_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='profilePic',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='sector',
            field=models.ForeignKey(default='Info & Tech', on_delete=django.db.models.deletion.CASCADE, to='profiles.sector', to_field='sector'),
        ),
    ]
