# Generated by Django 3.2.6 on 2021-11-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20211129_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='companyLogo',
        ),
    ]
