# Generated by Django 3.2.6 on 2021-11-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_remove_recruiterprofile_companylogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='employees',
            field=models.IntegerField(default=1),
        ),
    ]
