# Generated by Django 3.2.6 on 2021-11-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_recruiterprofile_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='webSite',
            field=models.URLField(blank=True),
        ),
    ]
