# Generated by Django 3.2.6 on 2021-12-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_rename_userskills_userskill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='companyTypes',
            new_name='companyType',
        ),
    ]
