# Generated by Django 3.2.6 on 2021-12-10 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_auto_20211210_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='isPresent',
            new_name='isOngoing',
        ),
        migrations.AddField(
            model_name='education',
            name='isOngoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='position',
            field=models.ForeignKey(default='position', on_delete=django.db.models.deletion.CASCADE, to='profiles.positions', to_field='position'),
        ),
    ]
