# Generated by Django 3.2.6 on 2021-12-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_auto_20211210_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
