# Generated by Django 3.2.6 on 2021-12-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_alter_experience_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
