# Generated by Django 3.2.6 on 2021-12-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_alter_education_enddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='about',
            new_name='bio',
        ),
    ]
