# Generated by Django 3.2.6 on 2021-12-22 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0021_auto_20211222_1110'),
        ('profiles', '0036_rename_about_profilemodel_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='skill',
        ),
        migrations.AddField(
            model_name='userskill',
            name='label',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='offers.skill', to_field='label'),
        ),
    ]
