# Generated by Django 3.2.6 on 2021-12-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_auto_20211222_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companytype',
            old_name='_type',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='positions',
            old_name='position',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='sector',
            new_name='label',
        ),
    ]
