# Generated by Django 3.2.6 on 2021-12-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '__first__'),
        ('profiles', '0038_auto_20211222_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.degree', to_field='label'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.institute', to_field='label'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.position', to_field='label'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='position',
            field=models.ForeignKey(default='position', on_delete=django.db.models.deletion.CASCADE, to='common.position', to_field='label'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='companyType',
            field=models.ForeignKey(default='Start-up', on_delete=django.db.models.deletion.CASCADE, to='common.companytype', to_field='label'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='sector',
            field=models.ForeignKey(default='Info & Tech', on_delete=django.db.models.deletion.CASCADE, to='common.sector', to_field='label'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='label',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.skill', to_field='label'),
        ),
        migrations.DeleteModel(
            name='companyType',
        ),
        migrations.DeleteModel(
            name='Degrees',
        ),
        migrations.DeleteModel(
            name='Positions',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
