# Generated by Django 3.2.6 on 2021-12-25 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0039_auto_20211224_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='userLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.language', to_field='label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
