# Generated by Django 3.2.6 on 2021-12-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_studyfield'),
        ('profiles', '0040_userlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='field',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.studyfield', to_field='label'),
        ),
    ]
