# Generated by Django 3.2.6 on 2021-12-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_education_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
