# Generated by Django 3.2.6 on 2022-03-29 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0005_studyfield'),
        ('profiles', '0042_education_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='experienceInPosition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='postalCode',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.CreateModel(
            name='WishedPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.contracttype', to_field='label')),
                ('jobType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.offertype', to_field='label')),
                ('position', models.ForeignKey(default='position', on_delete=django.db.models.deletion.CASCADE, to='common.position', to_field='label')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsWhichedForPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userskill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
