# Generated by Django 3.2.6 on 2021-08-14 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0011_alter_offer_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condidate_Id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='applicantion_owner', to=settings.AUTH_USER_MODEL)),
                ('employer_Id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='offer_owner', to=settings.AUTH_USER_MODEL)),
                ('offerId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='offer_id', to='offers.offer')),
            ],
        ),
    ]
