# Generated by Django 3.2.6 on 2021-08-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='condidate_Id',
            new_name='condidateId',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='employer_Id',
            new_name='employerId',
        ),
    ]
