# Generated by Django 3.2.6 on 2021-10-09 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_profilemodel_user_id'),
        ('applications', '0004_alter_applications_condidate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='condidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicantion_owner', to='profiles.profilemodel'),
        ),
    ]
