# Generated by Django 3.2.6 on 2021-12-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_applications_condidate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='condidate_id',
            new_name='condidate',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='employer_id',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='offer_id',
            new_name='offer',
        ),
    ]
