# Generated by Django 3.2.6 on 2021-12-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20211212_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='condidate',
            new_name='candidate',
        ),
    ]
