# Generated by Django 3.2.6 on 2021-12-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='studyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=150, unique=True)),
            ],
        ),
    ]
