# Generated by Django 3.2.6 on 2021-08-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_usertypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_type',
            field=models.ForeignKey(default='condidate', on_delete=django.db.models.deletion.CASCADE, to='authapp.usertypes', to_field='type'),
        ),
    ]
