# Generated by Django 3.2.6 on 2021-12-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_useraccount_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userTypes',
            new_name='userType',
        ),
    ]
