# Generated by Django 3.2.6 on 2021-08-11 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='experienceYears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='offerCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(choices=[(1, 'CDI'), (2, 'CDD'), (3, 'freelance'), (4, 'intern')], max_length=250)),
                ('contract_type', models.CharField(choices=[(1, 'CDI'), (2, 'CDD'), (3, 'freelance'), (4, 'intern')], default=(1, 'CDI'), max_length=255)),
                ('salary', models.IntegerField()),
                ('urgent', models.BooleanField(default=False)),
                ('job_type', models.CharField(choices=[(1, 'Full time'), (1, 'Part Time')], max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('is_featured', models.BooleanField(default=False)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offercategories', to_field='category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
