# Generated by Django 3.2.6 on 2021-08-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='skills_needed',
            field=models.JSONField(default={'skills': '[]'}),
        ),
    ]
