# Generated by Django 3.2.6 on 2021-08-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='contract_type',
            field=models.CharField(choices=[('1', 'CDI'), ('2', 'CDD'), ('3', 'freelance'), ('4', 'intern')], default=('1', 'CDI'), max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='experience',
            field=models.CharField(choices=[['0', 'less than a yea'], ['1', 'one year'], ['2', 'two years'], ['3', 'three years'], ['4', 'three years'], ['5', 'five years'], ['6', 'six years'], ['7', 'more than 6 years']], max_length=250),
        ),
        migrations.AlterField(
            model_name='offer',
            name='job_type',
            field=models.CharField(choices=[('1', 'Full time'), ('1', 'Part Time')], max_length=250),
        ),
    ]
