# Generated by Django 3.2.6 on 2021-08-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20210811_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceyears',
            name='experience',
            field=models.CharField(max_length=250),
        ),
    ]
