# Generated by Django 3.2.6 on 2021-08-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_experienceyears_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='experience',
            field=models.CharField(choices=[('0', 'less than a yea'), ('1', 'one year'), ('2', 'two years'), ('3', 'three years'), ('4', 'three years'), ('5', 'five years'), ('6', 'six years'), ('7', 'more than 6 years')], max_length=250),
        ),
    ]
