# Generated by Django 3.2.6 on 2021-08-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_offer_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='skills_needed',
            new_name='skills',
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='job_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='offers.offercategories', to_field='category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
    ]
