# Generated by Django 3.2.6 on 2021-08-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20210813_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='contract_type',
            new_name='contractType',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='is_featured',
            new_name='isFeatured',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='job_category',
            new_name='jobCategory',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='job_title',
            new_name='jobTitle',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='job_type',
            new_name='jobType',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='user_id',
            new_name='userId',
        ),
    ]
