# Generated by Django 3.2.6 on 2021-08-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_auto_20210813_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='jobCategory',
            new_name='offerCategory',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='contractType',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='isFeatured',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='jobTitle',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='jobType',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='urgent',
        ),
        migrations.AddField(
            model_name='offer',
            name='offerTitle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='offerType',
            field=models.CharField(choices=[('1', 'CDI'), ('2', 'CDD'), ('3', 'freelance'), ('4', 'intern')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='experience',
            field=models.CharField(choices=[('0', 'less than a yea'), ('1', 'one year'), ('2', 'two years'), ('3', 'three years'), ('4', 'three years'), ('5', 'five years'), ('6', 'six years'), ('7', 'more than 6 years')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='skills',
            field=models.TextField(default=''),
        ),
    ]
