# Generated by Django 3.2.6 on 2021-08-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_auto_20210828_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
