# Generated by Django 3.2.6 on 2021-08-31 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_alter_skills_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='offerTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(default='', max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='offers.offertypes', to_field='_type'),
        ),
    ]
