# Generated by Django 3.2.6 on 2021-08-31 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_auto_20210831_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='createdAt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
