# Generated by Django 3.2.6 on 2021-12-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_recruiterprofile_website'),
        ('offers', '0015_offer_createdat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
