# Generated by Django 3.2.6 on 2021-12-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_rename_skills_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='offerCategories',
            new_name='offerCategorie',
        ),
    ]
