# Generated by Django 3.2.6 on 2021-12-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_rename_companytypes_companytype'),
        ('offers', '0017_rename_offercategories_offercategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='companyProfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.recruiterprofile'),
        ),
    ]
