# Generated by Django 3.2.6 on 2021-12-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0019_alter_offer_companyprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='contract_type',
            new_name='contractType',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='salary',
            new_name='maxSalary',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='offer_type',
            new_name='offerType',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='offer_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='offer',
            name='minSalary',
            field=models.IntegerField(default=0),
        ),
    ]
