# Generated by Django 3.2.6 on 2021-12-22 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0020_auto_20211211_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='offerskills',
            name='skill',
        ),
        migrations.AddField(
            model_name='offerskills',
            name='label',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='offers.skill', to_field='label'),
        ),
    ]
