# Generated by Django 3.2.6 on 2021-12-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0021_auto_20211222_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracttype',
            old_name='contract_type',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='offercategorie',
            old_name='category',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='offertypes',
            old_name='_type',
            new_name='label',
        ),
    ]
