# Generated by Django 3.2.6 on 2021-12-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '__first__'),
        ('offers', '0022_auto_20211222_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='contractType',
            field=models.ForeignKey(default='CDD', on_delete=django.db.models.deletion.SET_DEFAULT, to='common.contracttype', to_field='label'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.offertype', to_field='label'),
        ),
        migrations.AlterField(
            model_name='offerskills',
            name='label',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.skill', to_field='label'),
        ),
        migrations.DeleteModel(
            name='contractType',
        ),
        migrations.DeleteModel(
            name='offerTypes',
        ),
    ]
